version: '3'

vars:
  CONTAINER_CMD:
    sh: |
      if command -v podman >/dev/null 2>&1; then
        echo "podman"
      elif command -v docker >/dev/null 2>&1; then
        echo "docker"
      else
        echo "echo 'Error: No container runtime found (tried: podman, docker)' >&2 && exit 1"
      fi

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  test:
    desc: Run BATS tests using container runtime
    cmds:
      - echo "Running BATS tests..."
      - echo "Using container runtime{{":"}} {{.CONTAINER_CMD}}"
      - "{{.CONTAINER_CMD}} run --rm -v .:/plugin:ro -w /plugin buildkite/plugin-tester bats tests/"

  lint:
    desc: Run Buildkite plugin linter
    cmds:
      - echo "Running Buildkite plugin linter..."
      - echo "Using container runtime{{":"}} {{.CONTAINER_CMD}}"
      - "{{.CONTAINER_CMD}} run --rm -v .:/plugin:ro -w /plugin buildkite/plugin-linter --id StacklokLabs/toolhive"

  shellcheck:
    desc: Run shellcheck on hook scripts
    cmds:
      - echo "Running shellcheck on hooks..."
      - echo "Using container runtime{{":"}} {{.CONTAINER_CMD}}"
      - "{{.CONTAINER_CMD}} run --rm -v .:/plugin:ro -w /plugin koalaman/shellcheck-alpine:stable shellcheck hooks/*"

  all:
    desc: Run all checks (lint, shellcheck, test)
    deps: [lint, shellcheck, test]

  clean:
    desc: Clean up containers and images
    cmds:
      - echo "Cleaning up container resources..."
      - echo "Using container runtime{{":"}} {{.CONTAINER_CMD}}"
      - "{{.CONTAINER_CMD}} system prune -f"

  executable:
    desc: Make hooks executable (useful after git clone)
    cmds:
      - echo "Making hooks executable..."
      - chmod +x hooks/*

  validate:
    desc: Validate plugin.yml syntax
    cmds:
      - echo "Validating plugin.yml..."
      - python3 -c "import yaml; yaml.safe_load(open('plugin.yml'))"
      - echo "✅ plugin.yml is valid"

  syntax-check:
    desc: Run basic syntax check on hooks
    cmds:
      - echo "Checking hook syntax..."
      - |
        for hook in hooks/*; do
          echo "Checking $hook..."
          bash -n "$hook" || exit 1
        done
      - echo "✅ All hooks have valid syntax"

  dev-setup:
    desc: Set up development environment
    deps: [executable, validate, syntax-check]
    cmds:
      - echo "✅ Development environment ready"

  ci:
    desc: Run CI checks (for use in CI/CD)
    deps: [validate, syntax-check, lint, shellcheck, test]
    cmds:
      - echo "✅ All CI checks passed"