steps:
  - label: ":mag: Validate Plugin"
    agents:
      queue: staging
    command: |
      echo "Validating plugin configuration..."
      python3 -c "import yaml; yaml.safe_load(open('plugin.yml'))"
      echo "✅ plugin.yml is valid"

  - label: ":shell: Syntax Check"
    agents:
      queue: staging
    command: |
      echo "Checking shell script syntax..."
      for hook in hooks/*; do
        echo "Checking $hook..."
        bash -n "$hook" || exit 1
      done
      echo "✅ All hooks have valid syntax"

  - label: ":lint-roller: Plugin Linter"
    agents:
      queue: staging
    command: |
      echo "Running Buildkite plugin linter..."
      buildkite-plugin-linter --id StacklokLabs/toolhive .

  - label: ":bug: ShellCheck"
    agents:
      queue: staging
    command: |
      echo "Running ShellCheck on hooks..."
      shellcheck hooks/*

  - label: ":test_tube: BATS Tests"
    agents:
      queue: staging
    command: |
      echo "Running BATS tests..."
      bats tests/

  - label: ":white_check_mark: All Checks"
    agents:
      queue: staging
    depends_on:
      - "validate-plugin"
      - "syntax-check"
      - "plugin-linter"
      - "shellcheck"
      - "bats-tests"
    command: |
      echo "✅ All checks passed successfully!"
      echo "Plugin is ready for release"

  # Commenting this out since we're running CI on a very locked down cluster.
  # - label: ":package: Test Plugin Usage"
  #   command: |
  #     echo "Testing plugin with a simple MCP server..."
  #     echo "This would normally test the plugin in a real pipeline"
  #   plugins:
  #     - ./.:
  #         server: "fetch"
  #         name: "test-fetch-server"
  #         cleanup: true
  #   if: build.branch == "main"
